apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-depl
  labels:
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
      tier: backend
  template:
    metadata:
      labels:
        app: client
        tier: backend
    spec:
      containers:
        - name: client
          image: hugowuang701/client
          env:
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: client-srv
  labels:
    tier: backend
spec:
  selector:
    app: client
    tier: backend
  ports:
    - name: client
      protocol: TCP
      port: 3000
      targetPort: 3000
