apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-depl
  labels:
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders
      tier: backend
  template:
    metadata:
      labels:
        app: orders
        tier: backend
    spec:
      containers:
        - name: orders
          image: hugowuang701/orders
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: ticketing
            - name: MONGO_URI
              value: 'mongodb://orders-mongo-srv:27017/orders'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: orders-srv
  labels:
    tier: backend
spec:
  selector:
    app: orders
    tier: backend
  ports:
    - name: orders
      protocol: TCP
      port: 3002
      targetPort: 3002
