apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-depl
  labels:
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments
      tier: backend
  template:
    metadata:
      labels:
        app: payments
        tier: backend
    spec:
      containers:
        - name: payments
          image: hugowuang701/payments
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: ticketing
            - name: MONGO_URI
              value: 'mongodb://payments-mongo-srv:27017/payments'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: STRIPE_KEY
              valueFrom:
                secretKeyRef:
                  name: stripe-secret
                  key: STRIPE_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: payments-srv
  labels:
    tier: backend
spec:
  selector:
    app: payments
    tier: backend
  ports:
    - name: payments
      protocol: TCP
      port: 3003
      targetPort: 3003
